import { DB } from "kysely-codegen"; // the interface generated by kysely-codegen
import { Pool } from "pg";
import { Kysely, PostgresDialect } from "kysely";
import { envs } from "../../../adapters/envs";

const dialect = new PostgresDialect({
  pool: new Pool({
    database: envs.POSTGRES_DB,
    host: "localhost",
    user: envs.POSTGRES_USER,
    password: envs.POSTGRES_PASSWORD,
    port: 5432,
    max: 10,
  }),
});

// Database interface is passed to Kysely's constructor, and from now on, Kysely
// knows your database structure.
// Dialect is passed to Kysely's constructor, and from now on, Kysely knows how
// to communicate with your database.
export const kysely = new Kysely<DB>({
  dialect,
});
